#!/usr/bin/env python3
"""Central bilingual copy for AgoraLink secondary screens."""

from __future__ import annotations

from typing import Dict


COPY: Dict[str, Dict[str, str]] = {
    "zh": {
        "settings": "设置",
        "settings_description": "管理 AgoraLink 的设备、传输和屏幕共享选项。",
        "general": "常规",
        "general_description": "管理语言、设备名称和应用行为。",
        "network": "网络与发现",
        "network_description": "查看此设备的局域网连接和接收状态。",
        "transfer": "文件传输",
        "transfer_description": "设置文件保存位置和传输偏好。",
        "screen": "屏幕共享",
        "screen_description": "配置屏幕共享的画质、声音与连接选项。",
        "privacy": "隐私与安全",
        "privacy_description": "管理受信任设备、聊天数据和确认行为。",
        "storage": "存储与诊断",
        "storage_description": "查看存储位置、运行状态并导出诊断信息。",
        "about": "关于",
        "about_description": "查看版本、构建和内置组件信息。",
        "save_changes": "保存更改",
        "cancel": "取消",
        "close": "关闭",
        "restore_defaults": "恢复默认",
        "reset_section": "恢复本页默认值",
        "reset_all": "恢复全部默认值",
        "advanced": "高级设置",
        "advanced_description": "面向故障排查和特殊网络环境的选项。",
        "enabled": "已启用",
        "disabled": "已关闭",
        "available": "可用",
        "unavailable": "不可用",
        "automatic": "自动",
        "managed_automatically": "由 AgoraLink 自动管理",
        "browse": "浏览",
        "copy": "复制",
        "copied": "已复制",
        "apply_next_share": "将在下次屏幕共享时生效",
        "needs_restart": "重新启动后生效",
        "invalid_value": "请输入有效值。",
        "value_out_of_range": "请输入 {minimum} 至 {maximum} 之间的值。",
        "changes_saved": "设置已保存",
        "changes_not_saved": "设置未保存",
        "confirm_reset_title": "恢复默认设置",
        "confirm_reset_message": "此操作会替换当前页面的设置。可以在保存前继续修改。",
        "confirm_danger": "确认此操作",
        "danger_irreversible": "此操作不可恢复。请确认后继续。",
        "technical_details": "技术详情",
        "security_details": "安全与技术信息",
        "current_status": "当前状态",
        "recheck": "重新检测",
        "open_logs": "打开日志目录",
        "export_diagnostics": "导出诊断包",
        "copy_technical_info": "复制技术信息",
        "diagnostics": "诊断",
        "status_summary": "状态摘要",
        "recent_errors": "最近错误",
        "no_recent_errors": "没有最近错误",
        "contact_details": "联系人详情",
        "contact_details_description": "查看联系人状态并开始常用操作。",
        "message": "发消息",
        "send_file": "发送文件",
        "share_screen": "共享屏幕",
        "edit_note": "编辑备注",
        "delete_contact": "删除联系人",
        "delete_contact_message": "将从本机删除该联系人及一对一聊天记录。此操作不可恢复。",
        "online": "在线",
        "offline": "离线",
        "trusted": "已信任",
        "group_management": "群组管理",
        "group_management_description": "查看成员、角色和群组操作。",
        "members": "成员",
        "add_member": "添加成员",
        "leave_group": "退出群组",
        "dissolve_group": "解散群组",
        "file_details": "文件传输详情",
        "file_details_description": "查看文件进度和可用操作。",
        "screen_details": "屏幕共享详情",
        "screen_details_description": "查看共享状态、画质、声音和连接质量。",
        "open_settings": "打开设置",
        "try_again": "再次尝试",
        "stop_sharing": "停止共享",
        "something_went_wrong": "操作未完成",
        "suggested_action": "建议操作",
        "empty_title": "暂无内容",
        "empty_description": "选择一个设备或会话以开始。",
    },
    "en": {
        "settings": "Settings",
        "settings_description": "Manage AgoraLink device, transfer, and screen sharing options.",
        "general": "General",
        "general_description": "Manage language, device name, and application behavior.",
        "network": "Network & Discovery",
        "network_description": "Review this device's local network connection and receive status.",
        "transfer": "File Transfer",
        "transfer_description": "Choose where files are saved and how transfers behave.",
        "screen": "Screen Sharing",
        "screen_description": "Configure screen sharing quality, sound, and connection options.",
        "privacy": "Privacy & Security",
        "privacy_description": "Manage trusted devices, chat data, and confirmation behavior.",
        "storage": "Storage & Diagnostics",
        "storage_description": "Review storage locations, runtime status, and diagnostic exports.",
        "about": "About",
        "about_description": "Review version, build, and bundled component information.",
        "save_changes": "Save changes",
        "cancel": "Cancel",
        "close": "Close",
        "restore_defaults": "Restore defaults",
        "reset_section": "Restore page defaults",
        "reset_all": "Restore all defaults",
        "advanced": "Advanced settings",
        "advanced_description": "Options for troubleshooting and unusual network environments.",
        "enabled": "Enabled",
        "disabled": "Off",
        "available": "Available",
        "unavailable": "Unavailable",
        "automatic": "Automatic",
        "managed_automatically": "Managed automatically by AgoraLink",
        "browse": "Browse",
        "copy": "Copy",
        "copied": "Copied",
        "apply_next_share": "Applies to the next screen share",
        "needs_restart": "Applies after restart",
        "invalid_value": "Enter a valid value.",
        "value_out_of_range": "Enter a value from {minimum} to {maximum}.",
        "changes_saved": "Settings saved",
        "changes_not_saved": "Settings were not saved",
        "confirm_reset_title": "Restore default settings",
        "confirm_reset_message": "This replaces the settings on the current page. You can still edit them before saving.",
        "confirm_danger": "Confirm this action",
        "danger_irreversible": "This action cannot be undone. Confirm to continue.",
        "technical_details": "Technical details",
        "security_details": "Security & technical information",
        "current_status": "Current status",
        "recheck": "Check again",
        "open_logs": "Open log folder",
        "export_diagnostics": "Export diagnostics",
        "copy_technical_info": "Copy technical information",
        "diagnostics": "Diagnostics",
        "status_summary": "Status summary",
        "recent_errors": "Recent errors",
        "no_recent_errors": "No recent errors",
        "contact_details": "Contact details",
        "contact_details_description": "Review contact status and start a common action.",
        "message": "Message",
        "send_file": "Send file",
        "share_screen": "Share screen",
        "edit_note": "Edit note",
        "delete_contact": "Delete contact",
        "delete_contact_message": "This removes the contact and direct chat history from this device. This cannot be undone.",
        "online": "Online",
        "offline": "Offline",
        "trusted": "Trusted",
        "group_management": "Group management",
        "group_management_description": "Review members, roles, and group actions.",
        "members": "Members",
        "add_member": "Add member",
        "leave_group": "Leave group",
        "dissolve_group": "Dissolve group",
        "file_details": "File transfer details",
        "file_details_description": "Review file progress and available actions.",
        "screen_details": "Screen sharing details",
        "screen_details_description": "Review sharing state, quality, sound, and connection health.",
        "open_settings": "Open settings",
        "try_again": "Try again",
        "stop_sharing": "Stop sharing",
        "something_went_wrong": "The action could not be completed",
        "suggested_action": "Suggested action",
        "empty_title": "Nothing here yet",
        "empty_description": "Choose a device or conversation to get started.",
    },
}


def normalize_lang(lang: object) -> str:
    return "en" if str(lang or "").strip().lower().startswith("en") else "zh"


def tr(lang: object, key: str, **kwargs: object) -> str:
    language = normalize_lang(lang)
    text = COPY.get(language, {}).get(key) or COPY["en"].get(key) or str(key)
    return text.format(**kwargs) if kwargs else text


def has_bilingual_copy(key: str) -> bool:
    return bool(COPY["zh"].get(key) and COPY["en"].get(key))
